dataplane url is standardized according to other sdks
rudderlabs/rudder-php-sdk pull request #2
Opened 2021-11-01 07:28 UTC by shrouti1507

## Description of the change
The protocol was hardcoded to `https://` previously, now it is done following the exact implementation of Segment.
> Description here

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2021-11-08 15:45 UTC, saikumarrs requested changes

2021-11-08 15:45 UTC, saikumarrs commented on lib/Rudder/Consumer/ForkCurl.php
> +    $url =  $protocol . $dataPlaneUrl . $path;
Fix the indentations

2021-11-08 15:45 UTC, saikumarrs commented on lib/Rudder.php
> +    // check if ssl is here --> check if it is http or https
Let's also validate the data plane URL input to make sure that it is a URL.

2021-11-09 09:55 UTC, shrouti1507 commented on lib/Rudder.php
> +    }
deleted the if condition and directly called handleSSL

2021-11-09 09:55 UTC, shrouti1507 commented on lib/Rudder/Consumer/ForkCurl.php
> +    $url =  $protocol . $dataPlaneUrl . $path;
done

2021-11-09 09:56 UTC, shrouti1507 commented on lib/Rudder.php
> +    // check if ssl is here --> check if it is http or https
done this using `filter_var($options["data_plane_url"], FILTER_VALIDATE_URL)`

2021-11-11 11:16 UTC, saikumarrs requested changes

2021-11-11 11:16 UTC, saikumarrs commented on lib/Rudder.php
> +    } }
Let's refactor this logic a bit (also combined the above suggestion) like below,

```suggestion
    if(<validate data plane input here>) {
      $protocol = "https";
      if($options["ssl"] == false) {
        $protocol = "http";
      }
      
      $options["data_plane_url"] = $this->handleUrl($options["data_plane_url"], $protocol);
    }
```

2021-11-11 11:58 UTC, shrouti1507 commented on lib/Rudder.php
> +    } }
done

2021-11-11 11:58 UTC, shrouti1507 commented on lib/Rudder.php
> +    if($options["ssl"] == 'true') { // if ssl is true only https is expected
done

2021-11-11 11:59 UTC, shrouti1507 commented on lib/Rudder.php
> +    if($options["ssl"] == 'true') { // if ssl is true only https is expected
done

2021-11-12 11:20 UTC, saikumarrs commented on lib/Rudder.php
> +      $errstr = ("The dataplane URL is null");
Let's change this to,

"'data_plane_url' option is required"

2021-11-12 11:20 UTC, saikumarrs commented on lib/Rudder.php
> +      self::handleSSL($options);
Please clone and send the '$options' object

2021-11-12 11:20 UTC, saikumarrs commented on lib/Rudder.php
> +      $errstr = ("The Dataplane URL is invalid");
Let's change it to something like below,

"'data_plane_url' input is invalid"

2021-11-23 09:18 UTC, MoumitaM commented on lib/Rudder.php
> +      $errstr = ("The dataplane URL is null");
done

2021-11-23 09:19 UTC, MoumitaM commented on lib/Rudder.php
> +      self::handleSSL($options);
Cloning is not needed as the handleSSL function is not modifying the actual $options.

2021-11-23 09:19 UTC, MoumitaM commented on lib/Rudder.php
> +      $errstr = ("The Dataplane URL is invalid");
done

2021-11-23 09:56 UTC, saikumarrs commented on lib/Rudder.php
> +      self::handleSSL($options);
In one of the cases, we are stripping the protocol of the URL and replacing it in the `$options` object

2021-11-24 05:20 UTC, MoumitaM commented on lib/Rudder.php
> +      self::handleSSL($options);
In one of the cases, we are stripping the protocol of the URL and replacing it in the $options object --- It was not happening and that actually caused the issue where extra protocol appended to the URL. 
Anyway, we need to do "stripping the protocol of the URL and replacing it in the $options object", otherwise if we keep the $options object unaltered then at a later point of time where the final URL is getting constructed one extra protocol will be added as a prefix.

2021-11-24 06:07 UTC, saikumarrs commented on lib/Rudder.php
> +      self::handleSSL($options);
Yes the cleanup of the URL is needed but it is not a good practice to alter the incoming arguments.

2021-11-24 09:52 UTC, MoumitaM commented on lib/Rudder.php
> +      self::handleSSL($options);
Done.

2021-11-24 11:00 UTC, saikumarrs commented on lib/Rudder.php
> +      self::handleSSL($options);
The solution sounds good but can you find out if there any corner cases (like date type values etc) with this approach.

2021-11-30 10:41 UTC, saikumarrs approved these changes

2021-11-30 10:45 UTC, merged